authors:
  xcrafttm:
    name: XCraftTM
    description: Supporter of DBB
    avatar: https://cdn.discordapp.com/avatars/301751879107477504/3faaa188015fc290be14a9ae73e88907.webp
  beastly:
    name: Beastlybear2017
    description: Supporter of DBB
    avatar: https://cdn.discordapp.com/avatars/513290137342574594/ddb75d1772cfa80c4392fc3421afd3ea.webp